=== SzAndras1/V9RN7C_XMLGyak/V9RN7C_0928/V9RN7C_ertodtd.dtd
<!ELEMENT ERmodell (A,AtoB,B,C)>
    <!ELEMENT A (Ab, Ac)>
        <!ATTLIST A Aa ID #REQUIRED>
        <!ELEMENT Ab (Abx, Aby)>
            <!ELEMENT Abx (#PCDATA)>
            <!ELEMENT Aby (#PCDATA)>
        <!ELEMENT Ac (Acd, Ace)>
            <!ELEMENT Acd (#PCDATA)>
            <!ELEMENT Ace (#PCDATA)>
    <!ELEMENT AtoB (AtoBc)>
        <!ATTLIST AtoB AtoBa IDREF #REQUIRED>
        <!ATTLIST AtoB AtoBb IDREF #REQUIRED>
        <!ELEMENT AtoBc (#PCDATA)>
    <!ELEMENT B (Bb)>
        <!ATTLIST B Ba ID #REQUIRED>
        <!ELEMENT Bb (Bbx, Bby)>
            <!ELEMENT Bbx (#PCDATA)>
            <!ELEMENT Bby (#PCDATA)>
    <!ELEMENT C (Cb)>
        <!ATTLIST C 
            Ca ID #REQUIRED
            CtoB IDREF #REQUIRED>
        <!ELEMENT Cb (#PCDATA)>

=== SzAndras1/V9RN7C_XMLGyak/V9RN7C_0928/V9RN7C_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ERmodell SYSTEM "V9RN7C_ertodtd.dtd">

<ERmodell>
    <A Aa="Element_1">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <AtoB AtoBa="Element_1" AtoBb="Element_2">
        <AtoBc></AtoBc>
    </AtoB>
    <B Ba="Element_2">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="Element_3" CtoB="Element_2">
        <Cb></Cb>
    </C>
</ERmodell>
