=== SzAndras1/V9RN7C_XMLGyak/XMLTaskV9RN7C/DomParseV9RN7C/V9RN7Cxml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--Egyszerű típusok-->
    <xs:simpleType name="hazszam_type" >
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,3}(/A|/a|/B|/b|/C|/c|/D|/d)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="utca_type" >
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z ]{3,}( utca| út| tér)" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="szint_type" >
        <xs:restriction base="xs:string">
            <xs:pattern value="(kezdő|közép|emelt)" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fizetes_type">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="200000" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Komplex típusok-->
    <xs:complexType name="tulajdonos_type">
        <xs:sequence>
            <xs:element name="cegnev" />
            <xs:element name="adoszam"/>
            <xs:element name="alapitas" />
            <xs:element name="bevetel"  />
        </xs:sequence>
        <xs:attribute name="t_id" use="required" />
        <xs:attribute name="fesz_t" use="required" />
    </xs:complexType>

    <xs:complexType name="fesztival_type">
        <xs:sequence>
            <xs:element name="nev"  />
            <xs:element name="helyszin"  />
            <xs:element name="ev" />
        </xs:sequence>
        <xs:attribute name="fesz_id" use="required" />
    </xs:complexType>

    <xs:complexType name="fellepo_type">
        <xs:sequence>
            <xs:element name="nev" />
            <xs:element name="orszag" />
            <xs:element name="dij"/>
        </xs:sequence>
        <xs:attribute name="fel_id" use="required" />
        <xs:attribute name="fesz_fel" use="required" />
    </xs:complexType>

    <xs:complexType name="bar_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="ital" maxOccurs="unbounded" />
            <xs:element name="cegnev" />
        </xs:sequence>
        <xs:attribute name="b_id" use="required" />
        <xs:attribute name="fesz_b" use="required" />
    </xs:complexType>

    <xs:complexType name="alkalmazott_type">
        <xs:sequence>
            <xs:element name="nev" />
            <xs:element name="fizetes" type="fizetes_type" />
            <xs:element name="muszak" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="a_id" use="required" />
        <xs:attribute name="b_a" use="required" />
    </xs:complexType>

    <xs:complexType name="lakcim_type">
        <xs:sequence>
            <xs:element name="telepules" type="xs:string"/>
            <xs:element name="utca" type="utca_type"/>
            <xs:element name="hazszam" type="hazszam_type" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="resztvevo_type">
        <xs:sequence>
            <xs:element name="nev" />
            <xs:element name="diakigazolvany" type="xs:boolean" />
            <xs:element name="lakcim" type="lakcim_type"></xs:element>
        </xs:sequence>
        <xs:attribute name="r_id" use="required" />
        <xs:attribute name="fesz_r" use="required" />
    </xs:complexType>

    <xs:complexType name="kozvelemeny_type">
        <xs:sequence>
            <xs:element name="kerdezo" />
        </xs:sequence>
        <xs:attribute name="r_k_r" use="required" />
        <xs:attribute name="ny_k_ny" use="required" />
    </xs:complexType>

    <xs:complexType name="nyelvtudas_type">
        <xs:sequence>
            <xs:element name="nyelv" type="xs:string"/>
            <xs:element name="szint" type="szint_type"/>
        </xs:sequence>
        <xs:attribute name="ny_id" use="required" />
    </xs:complexType>

    <!-- Gyökérelemtől az egyedek felhasználása -->
    <xs:element name="adatbazis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tulajdonos" type="tulajdonos_type"/>
                <xs:element name="fesztival" type="fesztival_type"/>
                <xs:element name="fellepo" type="fellepo_type" maxOccurs="unbounded" />
                <xs:element name="bar" type="bar_type" maxOccurs="unbounded" />
                <xs:element name="alkalmazott" type="alkalmazott_type" maxOccurs="unbounded" />
                <xs:element name="resztvevo" type="resztvevo_type" maxOccurs="unbounded" />
                <xs:element name="kozvelemeny" type="kozvelemeny_type" maxOccurs="unbounded" />
                <xs:element name="nyelvtudas" type="nyelvtudas_type" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok-->
        <xs:unique name="unique_tulajdonos">
            <xs:selector xpath="tulajdonos" />
            <xs:field xpath="@fesz_t" />
        </xs:unique>

        <xs:key name="fesztival_kulcs">
            <xs:selector xpath="fesztival" />
            <xs:field xpath="@fesz_id" />
        </xs:key>

        <xs:key name="fellepo_kulcs">
            <xs:selector xpath="fellepo" />
            <xs:field xpath="@fel_id" />
        </xs:key>

        <xs:key name="bar_kulcs">
            <xs:selector xpath="bar" />
            <xs:field xpath="@b_id" />
        </xs:key>

        <xs:key name="alkalmazott_kulcs">
            <xs:selector xpath="alkalmazott" />
            <xs:field xpath="@a_id" />
        </xs:key>

        <xs:key name="resztvevo_kulcs">
            <xs:selector xpath="resztvevo" />
            <xs:field xpath="@r_id" />
        </xs:key>

        <xs:key name="nyelvtudas_kulcs">
            <xs:selector xpath="nyelvtudas" />
            <xs:field xpath="@ny_id" />
        </xs:key>

        <!-- Idegen kulcsok-->
        <xs:keyref refer="fesztival_kulcs" name="fellepo_idegencs_kulcs">
            <xs:selector xpath="fellepo" />
            <xs:field xpath="@fesz_fel" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="bar_idegencs_kulcs">
            <xs:selector xpath="bar" />
            <xs:field xpath="@fesz_b" />
        </xs:keyref>

        <xs:keyref refer="bar_kulcs" name="alkalmazott_idegencs_kulcs">
            <xs:selector xpath="alkalmazott" />
            <xs:field xpath="@b_a" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="resztvevo_idegencs_kulcs">
            <xs:selector xpath="resztvevo" />
            <xs:field xpath="@fesz_r" />
        </xs:keyref>

        <xs:keyref refer="resztvevo_kulcs" name="resztvevo_k_idegencs_kulcs">
            <xs:selector xpath="kozvelemeny" />
            <xs:field xpath="@r_k_r" />
        </xs:keyref>

        <xs:keyref refer="nyelvtudas_kulcs" name="nyelvtudas_idegencs_kulcs">
            <xs:selector xpath="kozvelemeny" />
            <xs:field xpath="@ny_k_ny" />
        </xs:keyref>

    </xs:element>
</xs:schema>

=== SzAndras1/V9RN7C_XMLGyak/XMLTaskV9RN7C/V9RN7Cxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="V9RN7Cxml.xsd">
    <!--Tulajdonos -->
    <tulajdonos t_id="sgh-32h-j2" fesz_t="dh2-82k-ds">
        <cegnev>Providence Equity Partners</cegnev>
        <adoszam>312316312</adoszam>
        <alapitas>1989</alapitas>
        <bevetel>31000000000</bevetel>
    </tulajdonos>
    <!--Fesztivál -->
    <fesztival fesz_id="dh2-82k-ds">
        <nev>Balaton Sound</nev>
        <helyszin>Zamárdi</helyszin>
        <ev>2022</ev>
    </fesztival>
    <!--Fellépő -->
    <fellepo fel_id="312-sda-ma" fesz_fel="dh2-82k-ds">
        <nev>Paul Kalkbrenner</nev>
        <orszag>Németország</orszag>
        <dij>3000000</dij>
    </fellepo>
    <fellepo fel_id="wdn-w72-as" fesz_fel="dh2-82k-ds">
        <nev>Alesso</nev>
        <orszag>Svédország</orszag>
        <dij>6000000</dij>
    </fellepo>
    <fellepo fel_id="km7-h7g-2s" fesz_fel="dh2-82k-ds">
        <nev>Martin Garrix</nev>
        <orszag>Hollandia</orszag>
        <dij>7000000</dij>
    </fellepo>
    <!--Bár -->
    <bar b_id="ads-h2w-w2" fesz_b="dh2-82k-ds">
        <nev>Dreher bár</nev>
        <ital>Sör</ital>
        <ital>Vodka</ital>
        <ital>Whisky</ital>
        <cegnev>Dreher Sörgyárak Zrt.</cegnev>
    </bar>
    <bar b_id="mub-322-ds" fesz_b="dh2-82k-ds">
        <nev>Jana Aqua bár</nev>
        <ital>Ásványvíz</ital>
        <ital>Jägermeister</ital>
        <ital>Cognac</ital>
        <cegnev>AQUA Kft.</cegnev>
    </bar>
    <bar b_id="mnd-hb7-20" fesz_b="dh2-82k-ds">
        <nev>Foods and Drinks</nev>
        <ital>Vodka</ital>
        <ital>Energiaital</ital>
	<ital>Gin</ital>
        <cegnev>Zamardi Foods Kft.</cegnev>
    </bar>
    <!--Alkalmazott -->
    <alkalmazott a_id="mnh-hgf-j7" b_a="mub-322-ds">
        <nev>Dobos Sára</nev>
        <fizetes>321200</fizetes>
        <muszak>péntek-szombat</muszak>
        <muszak>szerda</muszak>
    </alkalmazott>
    <alkalmazott a_id="sha-dw7-wa" b_a="mnd-hb7-20">
        <nev>Papp Márton</nev>
        <fizetes>400000</fizetes>
        <muszak>szerda-péntek</muszak>
        <muszak>szombat</muszak>
    </alkalmazott>
    <alkalmazott a_id="dsa-wa6-42" b_a="mnd-hb7-20">
        <nev>Varga István</nev>
        <fizetes>410000</fizetes>
        <muszak>szombat</muszak>
        <muszak>csütörtök</muszak>
    </alkalmazott>
    
    <!--Résztvevő -->
    <resztvevo r_id="wda-312-s2" fesz_r="dh2-82k-ds">
        <nev>Pataki Patrícia</nev>
        <diakigazolvany>true</diakigazolvany>
        <lakcim>
            <telepules>Szombathely</telepules>
            <utca>Tolnai Lajos utca</utca>
            <hazszam>23</hazszam>
        </lakcim>
    </resztvevo>
    <resztvevo r_id="daw-29k-ws" fesz_r="dh2-82k-ds">
        <nev>Halász Milán</nev>
        <diakigazolvany>true</diakigazolvany>
        <lakcim>
            <telepules>Miskolc</telepules>
            <utca>Herend utca</utca>
            <hazszam>100</hazszam>
        </lakcim>
    </resztvevo>
    <resztvevo r_id="dwj-82w-sa" fesz_r="dh2-82k-ds">
        <nev>Somogyi Linda</nev>
        <diakigazolvany>false</diakigazolvany>
        <lakcim>
            <telepules>Karcag</telepules>
            <utca>Kardhegy utca</utca>
            <hazszam>33</hazszam>
        </lakcim>
    </resztvevo>

    <!--Közvélemény (kapcsolótábla) -->
    <kozvelemeny r_k_r="dwj-82w-sa" ny_k_ny="dag-213-sd">
        <kerdezo>Szűcs Vilmos</kerdezo>
    </kozvelemeny>
    <kozvelemeny r_k_r="dwj-82w-sa" ny_k_ny="kjg-mhz-2d">
        <kerdezo>Szűcs Vilmos</kerdezo>
    </kozvelemeny>
    <kozvelemeny r_k_r="daw-29k-ws" ny_k_ny="sk6-wss-31">
        <kerdezo>Jónás Judit</kerdezo>
    </kozvelemeny>
    <kozvelemeny r_k_r="wda-312-s2" ny_k_ny="jnu-21g-bs">
        <kerdezo>Szűcs Vilmos</kerdezo>
    </kozvelemeny>

    <!--Nyelvtudás -->
    <nyelvtudas ny_id="dag-213-sd">
        <nyelv>angol</nyelv>
        <szint>közép</szint>
    </nyelvtudas>
    <nyelvtudas ny_id="sk6-wss-31">
        <nyelv>angol</nyelv>
        <szint>emelt</szint>
    </nyelvtudas>
    <nyelvtudas ny_id="kjg-mhz-2d">
        <nyelv>német</nyelv>
        <szint>kezdő</szint>
    </nyelvtudas>
    <nyelvtudas ny_id="jnu-21g-bs">
        <nyelv>francia</nyelv>
        <szint>közép</szint>
    </nyelvtudas>
</adatbazis>
